version: '3.3'
services:
  web:
    build: 
     context: .
     dockerfile: Dockerfile
    env_file:
      - .env
    links:
      - db:${MYSQL_SERVER}
    volumes: 
      - ./web:/var/www/html
    ports:
      - ${APACHE_PORT}:80
    container_name: bibliotheque-public
    restart: always

  db:
    image: mysql:5.7
    container_name: mysql-bblthq
    restart: always
    ports:
      - "3310:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./files:/var/lib/mysql-files
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
